export const ROUTE_PATHS = {
  HOME: "Home",
  MAIN_HOME: "Main_Home",
  FAVORITES: "Favorites",
  OFFER: "Offer",
  BOOK: "Book",
  LOGIN: "Login",
  MAIN_MENU: "MainMenu",
  BOOK_READER: "BookReader",
  SHOP: "Shop",
  SHELVES_CONFIG: "Shelves_Config",
  SHELVES: "Shelves",
  CART: "Cart",
  CHECKOUT: "Checkout",
  SHOP_MENU: "ShopMenu",
  SHOP_SEARCH: "ShopSearch",
  SHOP_COLLECTIONS: "ShopCollections",
  SHOP_COLLECTION: "ShopCollection",
  SETTINGS: "Settings",
  BOOK_SHOP: "BookShop",
};
